---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    fabric8.io/git-commit: 9de6410d18e6e07c6f047f3ba1939a78cac5c175
    fabric8.io/git-branch: master
  labels:
    app: kafka-consumer-ocp
    provider: fabric8
    version: 0.0.1-SNAPSHOT
    group: org.redhat
  name: kafka-consumer-ocp
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    app: kafka-consumer-ocp
    provider: fabric8
    group: org.redhat
  strategy:
    rollingParams:
      timeoutSeconds: 3600
    type: Rolling
  template:
    metadata:
      annotations:
        fabric8.io/git-commit: 9de6410d18e6e07c6f047f3ba1939a78cac5c175
        fabric8.io/git-branch: master
      labels:
        app: kafka-consumer-ocp
        provider: fabric8
        version: 0.0.1-SNAPSHOT
        group: org.redhat
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: kafka-consumer-ocp:latest
        imagePullPolicy: IfNotPresent
        name: spring-boot
        ports:
        - containerPort: 9779
          name: prometheus
          protocol: TCP
        - containerPort: 8090
          protocol: TCP
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        securityContext:
          privileged: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - spring-boot
      from:
        kind: ImageStreamTag
        name: kafka-consumer-ocp:latest
    type: ImageChange
